### ISSUE TITLE
Unable to prepare route [eloquent_sheets_forget/{id?}] for serialization. Uses Closure.

### ISSUE THREAD

**Issue by shoover56** [grosv/eloquent-sheets#24]
When attempting to php artisan optimize, the following error returns:

 LogicException 

  Unable to prepare route [eloquent_sheets_forget/{id?}] for serialization. Uses Closure.

  at vendor/laravel/framework/src/Illuminate/Routing/Route.php:1081
    1077|      */
    1078|     public function prepareForSerialization()
    1079|     {
    1080|         if ($this->action['uses'] instanceof Closure) {
  > 1081|             throw new LogicException("Unable to prepare route [{$this->uri}] for serialization. Uses Closure.");
    1082|         }
    1083| 
    1084|         $this->compileRoute();
    1085| 

      +27 vendor frames 
  28  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

Using php 7.4.5.

**Comment by edgrosvenor** [comment]
@shoover56 Good find. Thanks. I replaced the closure in the routes file with a call to a controller so the route is now cacheable.
