### ISSUE TITLE
SQLite file created even when Sheets pull fails

### ISSUE THREAD

**Issue by mattstauffer** [grosv/eloquent-sheets#32]
If you, on first load of your application, have any errors connecting to the Sheets API (e.g. an auth error), it'll create the sqlite file but fail to fully migrate it, so on your next page load it'll show the table as missing (because the file exists but isn't migrated). Then you'll have to delete the SQLite file every time you load the page in order to re-create the actual issue.

- Discovered together pairing with @josecanhelp and @marcusmoore.

**Comment by edgrosvenor** [comment]
I don't love the solution I came up with for this. I'm hoping that when I remove the two layers of abstraction between this package and the Google API ( #38 ) that I'll be able to handle every circumstance in which something other than a good collection of sheet data is returned and bail out before the file is created. For now, I just look for an obvious problem (sheet data is not a collection), delete the file if it exists, and throw a generic exception.

**Comment by mattstauffer** [comment]
Thanks @edgrosvenor!
