### ISSUE TITLE
The inferId logic when inserting rows fails if any row has a null last column

### ISSUE THREAD

**Issue by mattstauffer** [grosv/eloquent-sheets#33]
I believe the solution is to move the inferId code at at the end, not the beginning, in sheetmodel:

![image](https://user-images.githubusercontent.com/151829/88111304-aea9c900-cb7b-11ea-97bd-3e6e22e2183f.png)

Otherwise, any row whose last column is null will have an error, because the ID column will have its data inserted one column too early.

- Discovered together pairing with @josecanhelp and @marcusmoore.

**Comment by edgrosvenor** [comment]
Well, it turned out to be a little trickier than just moving that block of code but I got it working.
