### ISSUE TITLE
Can Sushi be coaxed into making the json cache redundant?

### ISSUE THREAD

**Issue by edgrosvenor** [grosv/eloquent-sheets#4]
Currently Sushi doesn't cache between responses because we're using getRows() instead of a hard-coded rows array. But could it? Is there a good way to work around that limitation without adding a ton of complexity? 

Obviously I understand that in most cases it's probably not desirable to have Sushi cache dynamic data between responses, but since I have a mechanism built in for knowing when to forget the cache, the "should I do it?" question is less important than the "can I do it?" question.

**Comment by ryangjchandler** [comment]
Have you tried just adding `public $rows;` to the model. Sushi does a `property_exists()` check to determine whether it can be cached to file or not.
